name: unit-tests
on: [push, pull_request]
jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13
          platform: x64
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: nightly
      - name: Run Tests
        run: |
          uname -a
          export VIMPRG=${{ steps.vim.outputs.executable }}
          $VIMPRG --version
          cd test
          ./run_tests.sh
