name: unit-tests
on: [push, pull_request]
jobs:
  linux:
    name: linux
    runs-on: ubuntu-22.04
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y clangd-14
          sudo apt install -y curl
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash -
          sudo apt install -y nodejs
          sudo npm install -g typescript-language-server typescript
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: v9.0.0000
      - name: Checkout LSP Code
        uses: actions/checkout@v3
      - name: Run Tests
        run: |
          uname -a
          export VIMPRG=${{ steps.vim.outputs.executable }}
          $VIMPRG --version
          cd test
          ./run_tests.sh
